/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projectquanlynhanvien;

import com.mycompany.projectquanlynhanvien.NhanVien.JplDanhSachNhanVien;
import com.mycompany.projectquanlynhanvien.NhanVien.JplThongTinNhanVien;
import com.mycompany.projectquanlynhanvien.NhanVien.NhanVien;
import com.mycompany.projectquanlynhanvien.NhanVien.frmChangePassword;

import com.mycompany.projectquanlynhanvien.vuviec.JplDanhSachVuViec;
import com.mycompany.projectquanlynhanvien.vuviec.JplGiaoViec;
import java.awt.Graphics;

/**
 *
 * @author admin
 */
public class frmCuaSoChinh extends javax.swing.JFrame {

    /**
     * Creates new form frmCuaSoChinh
     */
    //Lưu trạng thái đăng nhập
    private static boolean trangThaiDangNhap = false;
    //Lưu thông tin người dùng đăng nhập
    private static NhanVien user = null;

    public static NhanVien getUser() {
        return user;
    }

    public static void setUser(NhanVien user) {
        frmCuaSoChinh.user = user;
    }

    public static boolean isTrangThaiDangNhap() {
        return trangThaiDangNhap;
    }

    public static void setTrangThaiDangNhap(boolean trangThaiDangNhap) {
        frmCuaSoChinh.trangThaiDangNhap = trangThaiDangNhap;
    }

    public frmCuaSoChinh() {
        initComponents();
        final boolean showTabsHeader = false;
        jTabMain.setUI(new javax.swing.plaf.metal.MetalTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                if (showTabsHeader) {
                    return super.calculateTabAreaHeight(tabPlacement, horizRunCount, maxTabHeight);
                } else {
                    return 0;
                }
            }

            protected void paintTabArea(Graphics g, int tabPlacement, int selectedIndex) {
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jblLogo = new javax.swing.JLabel();
        jTabMain = new javax.swing.JTabbedPane();
        jblChaoMung = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2CongViec = new javax.swing.JMenu();
        jMenuCongViec = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuDanhSach = new javax.swing.JMenu();
        jMenuDanhSachNhanVien = new javax.swing.JMenuItem();
        jMenuNghiepVu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuThongTinTaiKhoan = new javax.swing.JMenuItem();
        jMenuDangXuat = new javax.swing.JMenuItem();
        jMenuDoiMatKhau = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 0));
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HỆ THỐNG QUẢN LÝ NHÂN VIÊN VÀ GIAO VIỆC");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo-stanford.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jblChaoMung.setText("Chào mừng!");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 3.png"))); // NOI18N
        jMenu1.setText("Trang chủ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2CongViec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bar Chart.png"))); // NOI18N
        jMenu2CongViec.setText("Công việc");
        jMenu2CongViec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuCongViec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuCongViec.setText("Công Việc được giao");
        jMenuCongViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCongViecActionPerformed(evt);
            }
        });
        jMenu2CongViec.add(jMenuCongViec);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setText("Công Việc đã giao");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2CongViec.add(jMenuItem1);

        jMenuBar1.add(jMenu2CongViec);

        jMenuDanhSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book_edit.png"))); // NOI18N
        jMenuDanhSach.setText("Danh sách");
        jMenuDanhSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuDanhSachNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuDanhSachNhanVien.setText("Danh sách nhân viên");
        jMenuDanhSachNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDanhSachNhanVienActionPerformed(evt);
            }
        });
        jMenuDanhSach.add(jMenuDanhSachNhanVien);

        jMenuBar1.add(jMenuDanhSach);

        jMenuNghiepVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/action_settings.gif"))); // NOI18N
        jMenuNghiepVu.setText("Nghiệp vụ");
        jMenuNghiepVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem6.setText("Giao Việc");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuNghiepVu.add(jMenuItem6);

        jMenuBar1.add(jMenuNghiepVu);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-login-16x16.gif"))); // NOI18N
        jMenu6.setText("Tài khoản");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuThongTinTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuThongTinTaiKhoan.setText("Thông tin tài khoản");
        jMenuThongTinTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuThongTinTaiKhoanActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuThongTinTaiKhoan);

        jMenuDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuDangXuat.setText("Đăng Xuất");
        jMenuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDangXuatActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuDangXuat);

        jMenuDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuDoiMatKhau.setText("Đổi mật khẩu");
        jMenuDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDoiMatKhauActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuDoiMatKhau);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jblChaoMung, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabMain)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblChaoMung, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCongViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCongViecActionPerformed
        // TODO add your handling code here:
        JplDanhSachVuViec jplDanhSachVuViec = new JplDanhSachVuViec(user.getMaNV(),"Được Giao");
        jTabMain.removeAll();
        jTabMain.add(jplDanhSachVuViec);

    }//GEN-LAST:event_jMenuCongViecActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String maQuyen;

        if (user == null) {
            jblChaoMung.setText("Xin hãy đăng nhập tài khoản");
            jMenu2CongViec.setVisible(false);
            jMenuDanhSach.setVisible(false);
            jMenuNghiepVu.setVisible(false);
            jMenuDoiMatKhau.setVisible(false);
            jMenuThongTinTaiKhoan.setVisible(false);
            jMenuDangXuat.setText("Đăng Nhập");
        }
        if (user != null) {
            String name = user.getHoTen();
            jblChaoMung.setText("Chào mừng " + name);
            maQuyen = user.getMaQuyen();
            if (!maQuyen.equals("ADM")) {
                jMenuDanhSach.setVisible(false);
            }
        }
        jplAnhNen jplanhnen = new jplAnhNen();
        jTabMain.removeAll();
        jTabMain.add(jplanhnen);

    }//GEN-LAST:event_formWindowOpened

    private void jMenuThongTinTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuThongTinTaiKhoanActionPerformed
        // TODO add your handling code here:
        JplThongTinNhanVien jplThongTin = new JplThongTinNhanVien(user.getMaNV());
        jTabMain.removeAll();
        jTabMain.add(jplThongTin);
    }//GEN-LAST:event_jMenuThongTinTaiKhoanActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        JplGiaoViec jplGiaoViec = new JplGiaoViec();
        jplGiaoViec.setMaNhanVienHeThong(user.getMaNV());
        jTabMain.removeAll();
        jTabMain.add(jplGiaoViec);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuDanhSachNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDanhSachNhanVienActionPerformed
        // TODO add your handling code here:
        JplDanhSachNhanVien danhSachNhanVien = new JplDanhSachNhanVien();
        jTabMain.removeAll();
        jTabMain.add(danhSachNhanVien);
    }//GEN-LAST:event_jMenuDanhSachNhanVienActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JplDanhSachVuViec jplDanhSachVuViec = new JplDanhSachVuViec(user.getMaNV(),"Giao");
       
        jTabMain.removeAll();
        jTabMain.add(jplDanhSachVuViec);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDangXuatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        frmLogin frmlogin = new frmLogin();
        frmlogin.setVisible(true);
    }//GEN-LAST:event_jMenuDangXuatActionPerformed

    private void jMenuDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDoiMatKhauActionPerformed
        // TODO add your handling code here:
        frmChangePassword frmchangePassword = new frmChangePassword();
        frmchangePassword.setMk(user.getMatKhau());
        frmchangePassword.setMaNV(user.getMaNV());
        frmchangePassword.setVisible(true);
    }//GEN-LAST:event_jMenuDoiMatKhauActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        jplAnhNen jplanhnen = new jplAnhNen();
        jTabMain.removeAll();
        jTabMain.add(jplanhnen);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCuaSoChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2CongViec;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCongViec;
    private javax.swing.JMenuItem jMenuDangXuat;
    private javax.swing.JMenu jMenuDanhSach;
    private javax.swing.JMenuItem jMenuDanhSachNhanVien;
    private javax.swing.JMenuItem jMenuDoiMatKhau;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jMenuNghiepVu;
    private javax.swing.JMenuItem jMenuThongTinTaiKhoan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabMain;
    private javax.swing.JLabel jblChaoMung;
    private javax.swing.JLabel jblLogo;
    // End of variables declaration//GEN-END:variables
}
