/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projectquanlynhanvien.vuviec;

import com.mycompany.projectquanlynhanvien.NhanVien.NhanVien;
import com.mycompany.projectquanlynhanvien.NhanVien.NhanVienDao;
import com.mycompany.projectquanlynhanvien.NhanVien.NhanVienImpl;
import com.mycompany.projectquanlynhanvien.PhongBan.PhongBan;
import com.mycompany.projectquanlynhanvien.PhongBan.PhongBanDao;
import com.mycompany.projectquanlynhanvien.PhongBan.PhongBanImpl;
import com.mycompany.projectquanlynhanvien.PhongBan.PhongBanRender;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class JplGiaoViec extends javax.swing.JPanel {

    /**
     * Creates new form JplGiaoViec
     */
    public JplGiaoViec() {
        initComponents();
        txtPhongBan.setEnabled(false);
        txtNhanVien.setEnabled(false);
        hienThiDanhSachPhong();
    }
    static List<PhongBan> lstPhongBan = new ArrayList();
    private String tenPhong = "", maPhong = "", strNhanVien = "";
    private String strPhongBan = "";
    static List<NhanVien> lstNhanVien = new ArrayList();
    private int MaNhanVienHeThong = 0;

    public int getMaNhanVienHeThong() {
        return MaNhanVienHeThong;
    }

    public void setMaNhanVienHeThong(int MaNhanVienHeThong) {
        this.MaNhanVienHeThong = MaNhanVienHeThong;
    }

    public static List<NhanVien> getLstNhanVien() {
        return lstNhanVien;
    }

    public static void setLstNhanVien(List<NhanVien> lstNhanVien) {
        JplGiaoViec.lstNhanVien = lstNhanVien;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTieuDe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPhongBan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNhanVien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDungCongViec = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jDateChooserDeadline = new com.toedter.calendar.JDateChooser();
        btnGiaoViec = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        cboPhongBan = new javax.swing.JComboBox<>();
        btnXacNhan = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cboMucDo = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin công việc"));
        setPreferredSize(new java.awt.Dimension(1280, 577));

        jLabel1.setText("Tiêu đề:");

        txtTieuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTieuDeActionPerformed(evt);
            }
        });

        jLabel2.setText("Phòng Ban tiếp nhận");

        jLabel3.setText("Người tiếp nhận:");

        txtNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhanVienActionPerformed(evt);
            }
        });

        jLabel4.setText("Nội dung công việc");

        txtNoiDungCongViec.setColumns(20);
        txtNoiDungCongViec.setRows(5);
        jScrollPane1.setViewportView(txtNoiDungCongViec);

        jLabel5.setText("Thời hạn yêu cầu:");

        btnGiaoViec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book_edit.png"))); // NOI18N
        btnGiaoViec.setText("Giao Việc");
        btnGiaoViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaoViecActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.gif"))); // NOI18N
        btnXoa.setText("Xóa bỏ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Group 3.png"))); // NOI18N
        btnNhanVien.setText("Chọn nhân viên tiếp nhận");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        cboPhongBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPhongBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboPhongBanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboPhongBanMousePressed(evt);
            }
        });
        cboPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPhongBanActionPerformed(evt);
            }
        });

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/renew.png"))); // NOI18N
        btnClean.setText("Xóa");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        jLabel6.setText("Mức độ: ");

        cboMucDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ít quan trọng", "Quan trọng", "Rất quan trọng" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(cboMucDo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnGiaoViec)
                                        .addGap(93, 93, 93))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(36, 36, 36)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnXoa)
                                        .addGap(52, 52, 52))))
                            .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 1112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClean)
                            .addComponent(txtTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 1112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 782, Short.MAX_VALUE)
                        .addComponent(jDateChooserDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClean)
                    .addComponent(txtPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhan))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboMucDo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addComponent(jDateChooserDeadline, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGiaoViec)
                    .addComponent(btnXoa))
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTieuDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTieuDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTieuDeActionPerformed

    
    private void btnGiaoViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaoViecActionPerformed
        // TODO add your handling code here:
        String strTieuDe = "", strNoiDung = "", strMucDo = "";
        strTieuDe = txtTieuDe.getText();
        strNoiDung = txtNoiDungCongViec.getText();
        strPhongBan = txtPhongBan.getText();
        strNhanVien = txtNhanVien.getText();

        if (strTieuDe.isEmpty()) {
            JOptionPane.showMessageDialog(getRootPane(), "Bạn cần phải nhập Tiêu đề");
            txtTieuDe.requestFocus();
            return;
        }
        if (strNoiDung.isEmpty()) {
            JOptionPane.showMessageDialog(getRootPane(), "Bạn cần phải nhập Nội dung công việc");
            txtNoiDungCongViec.requestFocus();
            return;
        }
        if (strPhongBan.isEmpty() && strNhanVien.isEmpty()) {
            JOptionPane.showMessageDialog(getRootPane(), "Bạn cần phải nhập Phòng Ban hoặc người tiếp nhận công việc");
            return;
        }
        VuViec objVV = new VuViec();
        objVV.setTenVuViec(strTieuDe);
        objVV.setMoTa(strNoiDung);
        objVV.setDateLine(jDateChooser1.getDate());
        java.util.Date date = new java.util.Date();
        objVV.setNgayBatDau(date);
        objVV.setTinhTrang(1);

        strMucDo = "" + cboMucDo.getSelectedItem();
        switch (strMucDo) {
            case "Ít quan trọng":
                objVV.setMucDoId(1);
                break;
            case "Quan trọng":
                objVV.setMucDoId(2);
                break;
            case "Rất quan trọng":
                objVV.setMucDoId(3);
                break;
        }
        objVV.setMaNguoiGiao(MaNhanVienHeThong);
        VuViecDao vuViecDao = new VuViecImpl();

        vuViecDao.themMoi(objVV);
        
        
        
        int maVV = 0;
        NhanVienDao nhanVienDao = new NhanVienImpl();
       
        maVV = vuViecDao.getMaVVMax();
        List<Integer> lstNV = new ArrayList();
        List<NhanVien> lstDSNV = new ArrayList();

        for (PhongBan pb : lstPhongBan) {
            lstDSNV = nhanVienDao.timKiemNhanVien("", pb.getMaPhong(), 0, 0);
            for (NhanVien nv : lstDSNV) {
                lstNhanVien.add(nv);
            }
        }

        for (NhanVien nv : lstNhanVien) {
            int temp = 0;
            for (int i = 0; i < lstNV.size(); i++) {
                if (nv.getMaNV() == lstNV.get(i)) {
                    temp++;
                }
            }
            if (temp == 0) {
                lstNV.add(nv.getMaNV());
            }
        }
        boolean kq = false;
        for (int i = 0; i < lstNV.size(); i++) {
            kq = vuViecDao.InsertNhanVien_VuViec(maVV, lstNV.get(i));
        }
        if (kq == true){
           JOptionPane.showMessageDialog(getRootPane(), "Thêm mới thành công"); 
        }
    }//GEN-LAST:event_btnGiaoViecActionPerformed

    private void cboPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPhongBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPhongBanActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:

        PhongBan objPhong = (PhongBan) cboPhongBan.getSelectedItem();

        tenPhong = objPhong.getTenPhong();
        if (!tenPhong.equals("---Chọn Phòng---")) {
            strPhongBan += tenPhong + ";";
            txtPhongBan.setText(strPhongBan);
            lstPhongBan.add(objPhong);
        }

    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        txtPhongBan.setText("");
        strPhongBan = "";
        lstPhongBan.clear();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        strNhanVien = txtNhanVien.getText();
        frmChonNhanVien frmchonNhanVien = new frmChonNhanVien();
        if (!strNhanVien.isEmpty()) {
            frmchonNhanVien.setStrNhanVien(strNhanVien);
            frmchonNhanVien.setLstNV(lstNhanVien);
        }
        frmchonNhanVien.setTrangThai("Thêm Mới");

        frmchonNhanVien.setVisible(true);

    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void txtNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhanVienActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        txtTieuDe.setText("");
        txtPhongBan.setText("");
        strPhongBan = "";
        lstPhongBan.clear();
        txtNhanVien.setText("");
        lstNhanVien.clear();
        jDateChooser1.cleanup();
        txtNoiDungCongViec.setText("");
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cboPhongBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboPhongBanMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_cboPhongBanMouseClicked

    private void cboPhongBanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboPhongBanMousePressed
        // TODO add your handling code here:
        PhongBan objPhong = (PhongBan) cboPhongBan.getSelectedItem();

        tenPhong = objPhong.getTenPhong();
        if (!tenPhong.equals("---Chọn Phòng---")) {
            strPhongBan += tenPhong + ";";
            txtPhongBan.setText(strPhongBan);
            lstPhongBan.add(objPhong);
        }
    }//GEN-LAST:event_cboPhongBanMousePressed
    private void hienThiDanhSachPhong() {
        //Khai báo 1 đối tượng để lấy danh sách khoa
        PhongBanDao phongBanDao = new PhongBanImpl();

        //Lấy danh sách khoa
        List<PhongBan> lstPhong = phongBanDao.layDanhSach();

        PhongBan root = new PhongBan();
        root.setMaPhong("");
        root.setTenPhong("---Chọn Phòng---");
        lstPhong.add(0, root);

        DefaultComboBoxModel model = new DefaultComboBoxModel();

        //Duyệt từng thông tin khoa để đưa vào model
        for (PhongBan objPhong : lstPhong) {
            model.addElement(objPhong);
        }

        //Hiển thị lên combobox
        cboPhongBan.setModel(model);

        //Chỉnh sửa lại hiển thị
        cboPhongBan.setRenderer(new PhongBanRender());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnGiaoViec;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMucDo;
    private javax.swing.JComboBox<String> cboPhongBan;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooserDeadline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextArea txtNoiDungCongViec;
    private javax.swing.JTextField txtPhongBan;
    private javax.swing.JTextField txtTieuDe;
    // End of variables declaration//GEN-END:variables

}
